# Generated by Django 5.1 on 2024-08-10 11:54

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=225)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
