# Generated by Django 5.1 on 2024-08-11 21:13

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.TextField(max_length=255),
        ),
    ]
