# Generated by Django 5.1 on 2024-08-12 01:49

from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('app_cadastro', '0003_alter_usuario_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id_teste', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=225)),
                ('idade', models.IntegerField()),
            ],
        ),
    ]
